rm(list=ls())

pkgs <- c("tools", "ggplot2", "data.table", "optparse", "dplyr", "patchwork", "gridExtra", "RColorBrewer")
# Install CRAN packages (if not already installed)
# .inst <- .packages %in% installed.packages()
# if(length(.packages[!.inst]) > 0) install.packages(.packages[!.inst])
# Load packages into session
invisible(lapply(pkgs, require, character.only=TRUE))
################################################################################################################
##### INPUT ####################################################################################################
option_list = list(
  make_option(c("-f", "--file"), type = "character", default = NULL,
              help = "file generated by the software DH with summary statistics.",
              metavar = "character"))

opt_parser = OptionParser(usage = "Rscript scripts/make_tb_summary_stats.R -f summary/DH/DH_CZA_CRAB_nongenic_WWSS_est.txt",
                          option_list=option_list,
                          description = "Generate csv table.")
opt = parse_args(opt_parser)

if (is.null(opt$file)) {
  print_help(opt_parser)
  stop("Missing input file.\n", call.=FALSE)
}

# con <- file('summary/DH/DH_CZA_WAVE_LEFT_nongenic_WWSS_est.txt', open = "r")

con <- file(opt$file, open = "r")
lines <- readLines(con)
fl <- strsplit(x = tools::file_path_sans_ext(basename(lines[1])), split = '_')[[1]]
n <- strsplit(x = tools::file_path_sans_ext(basename(lines[2])), split = '=')[[1]][2]
n <- as.integer(substr(x = n, start = 2, stop = nchar(n)))
seg <- strsplit(x = tools::file_path_sans_ext(basename(lines[6])), split = ':')[[1]][2]
seg <- as.integer(substr(x = seg, start = 2, stop = nchar(seg)))
D <- as.numeric(substr(x = lines[8],start = 14, stop = nchar(lines[8])))
pD <- as.numeric(substr(x = lines[9],start = 24, stop = nchar(lines[9])))
H <- as.numeric(substr(x = lines[11],start = 18, stop = nchar(lines[11])))
pH <- as.numeric(substr(x = lines[12],start = 24, stop = nchar(lines[12])))
pv <- as.numeric(substr(x = lines[14],start = 26, stop = nchar(lines[14])))
E <- as.numeric(substr(x = lines[16],start = 10, stop = nchar(lines[16])))
pE <- as.numeric(substr(x = lines[17],start = 24, stop = nchar(lines[17])))

if (fl[3]=='CRAB') {
  ot <- data.frame(ZONE = fl[2], ECOT = fl[3], Variant_type = fl[length(fl)-1], ANN = paste(fl[4:(length(fl)-2)], collapse = '_'),
                   segsites = seg, D = D, pD = pD, H = H, pH = pH, pvalue_DH = pv, E = E, pE = pE, n = n)
} else {
  ot <- data.frame(ZONE = fl[2], ECOT = paste(fl[3], fl[4], sep = '_'), Variant_type = fl[length(fl)-1],
                   ANN = paste(fl[5:(length(fl)-2)], collapse = '_'),
                   segsites = seg, D = D, pD = pD, H = H, pH = pH, pvalue_DH = pv, E = E, pE = pE, n = n)
}

if (file.exists('results/DH_estimates.csv')) {
  write.table(x = ot, file = 'results/DH_estimates.csv', append = TRUE, quote = FALSE, sep = ',', row.names = FALSE, col.names = FALSE)
} else {
  write.table(x = ot, file = 'results/DH_estimates.csv', append = FALSE, quote = FALSE, sep = ',', row.names = FALSE, col.names = TRUE)
}
