#!/usr/bin/env python3

import os

for root, dirs, files in os.walk("fastq"):
    if not files:
        continue
    prefix = os.path.basename(root)
    for f in files:
        os.rename(os.path.join(root, f), os.path.join(root, "{}_{}".format(prefix, f)))
